FROM nvidia/cuda:10.2-cudnn8-runtime-ubuntu18.04

# Add arch list to environment variable
ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

# pytorch
RUN conda install pytorch==1.7.0 torchvision cudatoolkit=10.2 -c pytorch

# torch-geometric
RUN pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
RUN pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
RUN pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
RUN pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
RUN pip install torch-geometric

# install ngspice 
# Get the prerequisites
RUN sudo apt-get update \ 
    && sudo apt-get install -y \
    libreadline6-dev

RUN cd /tmp \
    && wget https://versaweb.dl.sourceforge.net/project/ngspice/ng-spice-rework/old-releases/27/ngspice-27.tar.gz \
    && tar -zxvf ngspice-27.tar.gz \ 
    && cd ngspice-27 \
    && ./configure --enable-xspice --disable-debug --with-readline=yes --enable-openmp \
    && make \
    && sudo make install

COPY requirements.txt /tmp/requirements.txt
RUN conda install --file /tmp/requirements.txt
